version: 0.0.1

# Change default server ports
server:
  applicationConnectors:
  - type: http
    port: 9000
  adminConnectors:
  - type: http
    port: 9001

mongo:
  seeds:
  - host: localhost
    port: 27017
  database: lms